#!/bin/bash
cmd=""
if [ $(stat -c "%s" msg) -ge 10 ]	
then
	echo "vous avez recu plusieurs messages dans votre boite de message:"
	cat msg
	echo > msg
fi

echo -n "$1@$2>"
until [ "$cmd" == " exit" ]
do
	read -t 1 cmd	#user@machine> cmd
	if [ "$cmd" == "" ]
	then
		if [ $(stat -c "%s" msg) -ge 10 ]	
		then
			cat msg
			echo > msg
			echo -n "$1@$2>"
			continue
		fi
		continue
	fi
	#read -t 3 cmd	#user@machine> cmd
	cmd=" "$cmd
	arr=(${cmd/ /})
	if [ "${arr[0]}" == "who" ]
	then
		echo "who"
	elif [ "${arr[0]}" == "rusers" ]
	then
		echo "who"
	elif [ "${arr[0]}" == "rhost" ]
	then
		echo "who"
	elif [ "${arr[0]}" == "connect" ]
	then
		./connect ${arr[1]} ${arr[2]}
	elif [ "${arr[0]}" == "su" ]
	then
		./su
	elif [ "${arr[0]}" == "finger" ]
	then
		echo "who"
	elif [ "${arr[0]}" == "write" -a ${#arr[*]} -ge 3 ]
	then
		msg=""
		len=$(expr ${#arr[*]} - 1)
		for i in $(seq 2 $len)
		do
			msg="$msg+${arr[i]}"
			echo $msg
		done
		./write ${arr[1]} $msg $1 $2	#write user@mac msg
	elif [ "${arr[0]}" == "passwd" ]
	then
		./password $1 $2
	elif [ "${arr[0]}" == "exit" ]
	then 
		sed -i "/$1 $2/d" ../status 	#enlever le status d'etre en linge
		break
	else 
		echo "echec,commande incorrecte"
	fi			
	echo -n "$1@$2>"
done
