#!/bin/bash
cmd=""
until [ "$cmd" == " exit" ]
do
	read -p "$1@$2>" cmd	#user@machine> cmd
	cmd=" "$cmd
	arr=(${cmd/ /})
	if [ "${arr[0]}" == "who" ]
	then
		echo "who"
	elif [ "${arr[0]}" == "rusers" ]
	then
		echo "who"
	elif [ "${arr[0]}" == "rhost" ]
	then
		echo "who"
	elif [ "${arr[0]}" == "connect" ]
	then
		echo "who"
	elif [ "${arr[0]}" == "su" ]
	then
		./su
	elif [ "${arr[0]}" == "finger" ]
	then
		echo "who"
	elif [ "${arr[0]}" == "write" -a ${#arr[*]} -eq 3 ]
	then
		./write ${arr[1]} ${arr[2]} $1 $2
	elif [ "${arr[0]}" == "passwd" ]
	then
		./password $1 $2
	elif [ "${arr[0]}" == "exit" ]
	then 
		break
	else 
		echo "echec,commande incorrecte"
	fi			
done
