#!/bin/bash

chmod +rw passwd
correct=0
while [ $correct -le 3 ]
do
	echo -n "le nouveau mot de passe: "
	read -s pswd
	echo ""
	echo -n "verifier le mot de passe: "
	read -s npswd
	echo ""
	if [ $pswd == $npswd ]
	then
		echo "$pswd" > passwd
		chmod 000 passwd
		sed  -i "s/$1 $2.*/$1 $2 $pswd/g"   ../known_hosts
		echo "vous avez change le mot de passe"
		break
	else
		correct=$(expr $correct + 1)
		echo "echec,le deuxiem mot de passe est different"
	fi
done

