#!/bin/bash

chmod +rw passwd
read -p "new password: " pswd
echo "$pswd" > passwd
chmod 000 passwd
sed  -i "s/$1 $2.*/$1 $2 $pswd/g"   ../known_hosts
if [ $? -eq 0 ]
then
	echo "vous avez change le mot de passe"
else
	echo "echec,raison inconnu"
fi
