#!/bin/bash

if [ $(grep -ce "$1 " known_hosts) -eq 0 -o $(grep -ce " $2 " known_hosts) -eq 0 ]	#这个判断条件还要改
then
	echo $ERR_USER
	exit
else 
	echo -n "password: "
	read -s passwd
	login=0
	while read line
	do
		count=0
		line=" "$line
		array=(${line/ /})
		if [ "$1" == "${array[0]}" -a "$2" == "${array[1]}" -a "$passwd" == "${array[2]}" ]
		then
			login=1
			break
		fi
	done < known_hosts
	if [ $login -eq 0 ]
	then
		echo "echec,mots de passe incorrects"
	else
		clear
		# 用户需要加 cd .. 
		cd $1@$2	#user@machine
		./main $1 $2
	fi
fi

