#!/bin/bash

chmod +rw known_hosts
if [ "$1" == "-add" ]      # host -add  pour ajouter un utilisateur
then
	read -p "nom d'utiisateur: " nom
	read -p "nom de machine: " nom_machine
	if [ -d $nom@$nom_machine ] 	# l'utilisateur doit deja exister
	then
		echo -n "mot de passe: "
		read -s mot_de_passe
		echo "$nom $nom_machine $mot_de_passe" >> known_hosts
		echo "fonction reussit"
	else
		echo "l'utilisateur n'existe pas"
		echo "vous devriez le creer par la commande <users>"
	fi
elif [ "$1" == "-del" ]	#host -del pour detruire
then
	read -p "nom d'utiisateur: " nom
	read -p "nom de machine: " nom_machine	
	if [ $(grep -ce "$nom $nom_machine" known_hosts) -ne 0 ]
	then
		sed -i "/$nom $nom_machine/d" known_hosts
		echo "fonction reussit"
	else
		echo "echec,utilisateur ou machine inconnu"
	fi
else
	echo $ERR_CMD		
fi
chmod 000 known_hosts
