#!/bin/bash

if [ "$1" == "host" -a "$2" == "-add" ]      # host -add  pour ajouter un utilisateur
then
	read -p "nom d'utiisateur: " nom
	read -p "nom de machine: " nom_machine
	read -p "mot de passe: " mot_de_passe
	echo "$nom $nom_machine $mot_de_passe" >> known_hosts
	echo "fonction reussit"
elif [ "$1" == "host" -a "$2" == "-del" ]	#host -del pour detruire
then
	read -p "nom d'utiisateur: " nom
	read -p "nom de machine: " nom_machine	
	if [ $(grep -ce "$nom $nom_machine" known_hosts) -ne 0 ]
	then
		sed -i "/$nom $nom_machine/d" known_hosts
		echo "fonction reussit"
	else
		echo "echec,utilisateur ou machine inconnu"
	fi
else
	echo $ERR_CMD		
fi
